### ISSUE TITLE
Gists set as private by default

### ISSUE THREAD

**Issue by ecosdelfuturo** [danielb2/joplin-publish#2]
The generated gists are set as private by default and I have to set them as public from my github account. Any workaround to this?

**Comment by danielb2** [comment]
not currently, but I can make it an option in the settings as to what type of gist to create

**Comment by ecosdelfuturo** [comment]
That would be great. Thanks for your quick answer!

**Comment by danielb2** [comment]
FYI I released 1.2.0 https://www.npmjs.com/package/joplin-plugin-publish

Let me know how this works for you

**Comment by ecosdelfuturo** [comment]
It works flawless. Thank you!
